Repository sungjin2836/turngame, pull requests merged in 2024-06, with the labels that each got.

#13 KAN-37 턴제 전투 진입 후 카메라
  Assets/Prefabs.meta
  Assets/Scenes/DataSample.unity
  Assets/Scripts/Battle/BattleCamera.cs
  Assets/Scripts/Battle/BattleCamera.cs.meta
  Assets/Scripts/Custom/DebugBattleCamera.cs
  Assets/Scripts/Custom/DebugBattleCamera.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
Labels: enhancement

#18 KAN-69-heal-item-structure
  Assets/Resources/Data/Items.json
  Assets/Resources/Data/Items.json.meta
  Assets/Scripts/Battle/BattleTurnManager.cs
  Assets/Scripts/Manager/ItemDataManager.cs
  Assets/Scripts/Manager/ItemDataManager.cs.meta
Labels: enhancement

#19 KAN-67 키보드 조작을 위한 키 할당
  Assets/Scripts/Battle/BattleCamera.cs
  Assets/Scripts/Custom/DebugBattleCamera.cs
  Assets/Scripts/PlayerInput.cs
  Assets/Scripts/PlayerInput.cs.meta
Labels: enhancement

#23 KAN-62 캐릭터 UI 추가
  Assets/Prefabs/CharacterList UI.prefab
  Assets/Prefabs/CharacterList UI.prefab.meta
  Assets/Scenes/DataSample.unity
  Assets/Scripts/Custom/DebugCharacterList.cs
  Assets/Scripts/Custom/DebugCharacterList.cs.meta
  Assets/Scripts/UI/CharacterIcon.cs
  Assets/Scripts/UI/CharacterIcon.cs.meta
  Assets/Scripts/UI/CharacterList.cs
  Assets/Scripts/UI/CharacterList.cs.meta
Labels: enhancement

#31 KAN-92 데이터 관련 작업
  Assets/Prefabs/CharacterList UI.prefab
  Assets/Resources/Data/Player.json
  Assets/Scenes/DataSample.unity
  Assets/Scenes/DataSample.unity.meta
  Assets/Scripts/Character/Character.cs
  Assets/Scripts/Character/Player.cs
  Assets/Scripts/Manager/DataManager.cs
  Assets/Scripts/Manager/UserDataManager.cs
  Assets/Scripts/UI/CharacterList.cs
Labels: enhancement

#35 KAN-100-bugFix
  Assets/Scripts/Battle/BattleCamera.cs
  Assets/Scripts/Battle/BattleTurnManager.cs
  Assets/Scripts/Character/Player.cs
  Assets/Scripts/UI/CharacterList.cs
Labels: bug

#38 Kan 104 character list
  Assets/Prefabs/UI/CharacterList UI.prefab
  Assets/Prefabs/UI/CharacterList UI.prefab.meta
  Assets/Prefabs/UI/Pause/Field/FieldPauseMenu.prefab
  Assets/Scenes/CharacterListScene.unity
  Assets/Scenes/CharacterListScene.unity.meta
  Assets/Scripts/Character/Player.cs
  Assets/Scripts/PlayerInput.cs
  Assets/Scripts/UI/CharacterList.cs
  Assets/Scripts/UI/Pause/FieldPause.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: bug, enhancement
